#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop aesdsocket daemon
### END INIT INFO

# Path to the aesdsocket binary
DAEMON_PATH="/usr/bin/aesdsocket"

# Options to pass to the daemon
DAEMON_OPTS="-d"

# Daemon name (used in logs and such)
DAEMON_NAME="aesdsocket"

# Daemon PID file location
PIDFILE="/var/run/${DAEMON_NAME}.pid"

start() {
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON_PATH -- $DAEMON_OPTS
}

stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --signal TERM
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON_PATH $DAEMON_NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0

